Public Module VerbType
    Public ReadOnly Boil As String = NameOf(Boil)
    Public ReadOnly ChopWood As String = NameOf(ChopWood)
    Public ReadOnly CollectStick As String = NameOf(CollectStick)
    Public ReadOnly Cook As String = NameOf(Cook)
    Public ReadOnly Craft As String = NameOf(Craft)
    Public ReadOnly DigClay As String = NameOf(DigClay)
    Public ReadOnly Dismantle As String = NameOf(Dismantle)
    Public ReadOnly Drink As String = NameOf(Drink)
    Public ReadOnly Fill As String = NameOf(Fill)
    Public ReadOnly Fish As String = NameOf(Fish)
    Public ReadOnly Forage As String = NameOf(Forage)
    Public ReadOnly Inventory As String = NameOf(Inventory)
    Public ReadOnly MoveEast As String = NameOf(MoveEast)
    Public ReadOnly MoveNorth As String = NameOf(MoveNorth)
    Public ReadOnly MoveSouth As String = NameOf(MoveSouth)
    Public ReadOnly MoveWest As String = NameOf(MoveWest)
    Public ReadOnly Place As String = NameOf(Place)
    Public ReadOnly Recipedia As String = NameOf(Recipedia)
    Public ReadOnly Refuel As String = NameOf(Refuel)
End Module
