Public Module Constants
    Friend Const ROOM_COLUMNS = 19
    Friend Const ROOM_ROWS = 19
    Friend ReadOnly NEVER_MIND_CHOICE As String = NameOf(NEVER_MIND_CHOICE)
    Friend Const NEVER_MIND_TEXT = "Never Mind"
    Friend ReadOnly OK_CHOICE As String = NameOf(OK_CHOICE)
    Friend Const OK_TEXT = "OK"
    Friend ReadOnly EAT_CHOICE As String = NameOf(EAT_CHOICE)
    Friend Const EAT_TEXT = "Eat"
    Friend ReadOnly TRY_AGAIN_CHOICE As String = NameOf(TRY_AGAIN_CHOICE)
    Friend Const TRY_AGAIN_TEXT = "Try Again"
    Public ReadOnly HARD_DIFFICULTY As String = NameOf(HARD_DIFFICULTY)
    Public ReadOnly NORMAL_DIFFICULTY As String = NameOf(NORMAL_DIFFICULTY)
    Public ReadOnly EASY_DIFFICULTY As String = NameOf(EASY_DIFFICULTY)
    Public ReadOnly TUTORIAL_DIFFICULTY As String = NameOf(TUTORIAL_DIFFICULTY)
    Public ReadOnly TAKE_ALL_CHOICE As String = NameOf(TAKE_ALL_CHOICE)
    Public Const TAKE_ALL_TEXT = "Take All"
    Public ReadOnly DROP_ONE_CHOICE As String = NameOf(DROP_ONE_CHOICE)
    Public Const DROP_ONE_TEXT = "Drop One"
    Public ReadOnly DROP_HALF_CHOICE As String = NameOf(DROP_HALF_CHOICE)
    Public Const DROP_HALF_TEXT = "Drop Half"
    Public ReadOnly DROP_ALL_CHOICE As String = NameOf(DROP_ALL_CHOICE)
    Public Const DROP_ALL_TEXT = "Drop All"
    Public ReadOnly DISMANTLE_ONE_CHOICE As String = NameOf(DISMANTLE_ONE_CHOICE)
    Public Const DISMANTLE_ONE_TEXT = "Dismantle One"
    Public ReadOnly DISMANTLE_HALF_CHOICE As String = NameOf(DISMANTLE_HALF_CHOICE)
    Public Const DISMANTLE_HALF_TEXT = "Dismantle Half"
    Public ReadOnly DISMANTLE_ALL_CHOICE As String = NameOf(DISMANTLE_ALL_CHOICE)
    Public Const DISMANTLE_ALL_TEXT = "Dismantle All"
End Module
