Public Module StatisticType
    Public ReadOnly BumpLocationId As String = NameOf(BumpLocationId)
    Public ReadOnly Depletion As String = NameOf(Depletion)
    Public ReadOnly DismantleGeneratorId As String = NameOf(DismantleGeneratorId)
    Public ReadOnly Durability As String = NameOf(Durability)
    Public ReadOnly ForageGeneratorId As String = NameOf(ForageGeneratorId)
    Public ReadOnly Health As String = NameOf(Health)
    Public ReadOnly Hydration As String = NameOf(Hydration)
    Public ReadOnly Illness As String = NameOf(Illness)
    Public ReadOnly Resource As String = NameOf(Resource)
    Public ReadOnly Satiety As String = NameOf(Satiety)
    Public ReadOnly Score As String = NameOf(Score)
    Public ReadOnly Fuel As String = NameOf(Fuel)
    Public ReadOnly Recovery As String = NameOf(Recovery)
    Public ReadOnly Water As String = NameOf(Water)
    Public ReadOnly FishSlapCounter As String = NameOf(FishSlapCounter)
End Module
